apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-service
spec:
  selector:
    app: checker-backend
    name: backend  # Match the name of the backend container
  ports:
    - protocol: TCP
      port: 8000  # Port to expose on the service
      targetPort: 8000 #The port for the React.js application container
  type: LoadBalancer 

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend-service
spec:
  selector:
    app: checker-frontend
    name: frontend  # Match the name of the frontend container
  ports:
    - protocol: TCP
      port: 3000  # Port to expose on the service
      targetPort: 3000
  type: LoadBalancer 
